### ISSUE TITLE
Input html for KEGG mapper reconstruct results

### ISSUE THREAD

**Issue by ellyyuyang** [JulieMarieCharmillon/kegg_parser#1]
Hi, 

Thanks for developing this! I am wondering how to obtain the input files for this tool.

1. The "initial_tsv_file.tsv": What is this file and how should it look like?
2. The "KEGG Mapper – Reconstruct Result.html" for kegg_parser.py:
    What I did was simply "save as" the chrome webpage of the KEGG mapper reconstruction results as "webpage, Complete" and append ".html" as the end of the filename. And then I supplied this saved html to kegg_parser.py:

   `python3 kegg_parser.py kegg_mapper_results.html modules `

    However, it reports error:

   > Traceback (most recent call last):
   >   File "/kegg_parser/kegg_parser.py", line 474, in <module>
   >     write_modules_csv()
   >   File "/kegg_parser/kegg_parser.py", line 226, in write_modules_csv
   >     d=find_modules_ko_column()
   >   File "/kegg_parser/kegg_parser.py", line 160, in find_modules_ko_column
   >     d = find_modules_sous_cats()
   >   File "/kegg_parser/kegg_parser.py", line 118, in find_modules_sous_cats
   >     d=find_modules_cats()
   >   File "/kegg_parser/kegg_parser.py", line 92, in find_modules_cats
   >     d=find_modules_supercats()
   >   File "/kegg_parser/kegg_parser.py", line 50, in find_modules_supercats
   >     supercat_list.append(supercat1.string)
   > **AttributeError: 'NoneType' object has no attribute 'string'**
 
    Anything you would suggest me to do? 

Thanks!

Best regards,
Yu

**Comment by AshtoBashto** [comment]
Hi Yu,

I ran into the same issue on my Mac, and I found that a normal "Save As" (even as "Webpage, HTML only") doesn't capture the dynamically rendered content that the `kegg_parser.py` script expects — specifically the `<div id="list">` that contains all the KO/module information.

What worked for me was manually saving the **rendered** HTML using the browser's Developer Tools. Here's how I did it:

---

### Best Solution: Use “Save Rendered HTML” via Developer Tools (Chrome)

**Steps (tested on Mac using Chrome):**

1. Go to [KEGG Mapper – Reconstruct](https://www.genome.jp/kegg/mapper/reconstruct.html)
2. Paste your KO list and click **Execute**
3. Wait for the results to fully load — scroll down to make sure the modules/pathways are visible
4. Right-click anywhere on the page and select **Inspect** (or press `Cmd + Option + I`)
5. Go to the **Elements** tab
6. Right-click the topmost `<html>` tag
7. Choose **"Edit as HTML"** or **"Copy → Outer HTML"**
8. Paste the full contents into a plain text file using a code editor like VS Code or TextEdit (in plain text mode)
9. Save the file as something like `KEGG_Modules_FIXED.html`

This captures the **actual rendered DOM**, including the `<div id="list">...</div>` section that the parser depends on. Once saved, you can run the parser like this:

```bash
python3 kegg_parser.py KEGG_Modules_FIXED.html modules

**Comment by ellyyuyang** [comment]
This is awesome, thanks @AshtoBashto I will give it a try! 

Best,
Yu

**Comment by ak-watson** [comment]
This is great, thank you @AshtoBashto and @JulieMarieCharmillon! I was digging into doing this myself, and I'm relieved you beat me to it! I'll do some sanity checks on the results but seems to have worked perfectly!

**Comment by andremicc** [comment]
Hi @JulieMarieCharmillon,

here's also my thank you for developing this, especially because I found some weird behaviour of the R KEGGREST package.
I would like to ask again question 1 of @ellyyuyang: The "initial_tsv_file.tsv": What is this file and how should it look like?

Cheers
